version: '3.8'

services:
    backend_fast_api:
        build:
            context: .
            dockerfile: Dockerfile
        image: backend_fast_api:dev
        container_name: backend_fast_api    
        restart: unless-stopped
        ports:
            - "8000:8000"
        env_file:
            - .env