[tool.ruff]
line-length = 150
target-version = "py312"
fix = true
unsafe-fixes = false
exclude = [
    ".git",
    ".ruff_cache",
    ".venv",
    "venv",
    "__pypackages__",
    "node_modules",
    "dist",
    "build",
    "migrations",
]

[tool.ruff.lint]
select = [
    "E",    # pycodestyle errors
    "F",    # pyflakes
    "I",    # isort
    "N",    # pep8-naming
    "UP",   # pyupgrade
    "YTT",  # flake8-2020
    "ANN",  # flake8-annotations (for type hints)
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "ICN",  # flake8-import-conventions
    "ISC",  # flake8-implicit-str-concat
    "G",    # flake8-logging-format
    "PIE",  # flake8-pie
    "PYI",  # flake8-pyi
    "PT",   # flake8-pytest-style
    "RET",  # flake8-return
    "SIM",  # flake8-simplify
    "TID",  # flake8-tidy-imports
    "ARG",  # flake8-unused-arguments
    "ERA",  # eradicate
    "PD",   # pandas-vet
    "PGH",  # pygrep-hooks
    "PL",   # pylint
    "TRY",  # tryceratops
    "RUF",  # ruff-specific rules
    "COM",  # flake8-commas
]
ignore = ["E501", "TRY003", "PLR2004", "B008", "ARG001", "I001", "TRY301"]
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|dummy|unused)$"
extend-select = ["ANN401"]

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = false
suppress-dummy-args = true
suppress-none-returning = false
mypy-init-return = true
ignore-fully-untyped = false

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]  # access import bot not use in __init__.py
"test_*.py" = ["ANN001", "ANN201"]  # skip some type hints in test file

[tool.ruff.lint.isort]
combine-as-imports = true
force-sort-within-sections = true
known-first-party = ["src"]  # adapt follow project
known-third-party = ["pytest"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]

[tool.ruff.lint.pep8-naming]
classmethod-decorators = ["classmethod", "validator", "root_validator"]

[tool.ruff.lint.flake8-type-checking]
strict = true

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true